CREATE DATABASE worldcup;

CREATE TABLE teams();
CREATE TABLE games();

ALTER TABLE teams ADD COLUMN team_id SERIAL PRIMARY KEY;
ALTER TABLE teams ADD COLUMN name VARCHAR(250) NOT NULL UNIQUE;

ALTER TABLE games ADD COLUMN game_id SERIAL PRIMARY KEY;
ALTER TABLE games ADD COLUMN year INT NOT NULL;
ALTER TABLE games ADD COLUMN round VARCHAR(250) NOT NULL;
ALTER TABLE games ADD COLUMN winner_id INT NOT NULL REFERENCES teams(team_id);
ALTER TABLE games ADD COLUMN opponent_id INT NOT NULL REFERENCES teams(team_id);
ALTER TABLE games ADD COLUMN winner_goals INT NOT NULL;
ALTER TABLE games ADD COLUMN opponent_goals INT NOT NULL;



